
import { Card, CardContent } from "@/components/ui/card";
import { Star, Quote } from "lucide-react";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";

const testimonials = [
  {
    name: "Sarah Johnson",
    role: "Podcast Host, Tech Talks",
    content: "Podion AI transformed my workflow completely. What used to take me 6 hours of content creation now takes just 30 minutes. The SEO blog posts drive 300% more traffic to my podcast!",
    rating: 5,
    avatar: "SJ"
  },
  {
    name: "Mike Chen",
    role: "Creator, Business Insights Pod",
    content: "The social media captions generated by Podion AI are spot-on. My engagement rates have doubled since I started using it. It's like having a content team in my pocket.",
    rating: 5,
    avatar: "MC"
  },
  {
    name: "Emily Rodriguez",
    role: "Host, Creative Minds",
    content: "I was skeptical about AI-generated content, but Podion AI gets my voice perfectly. The show notes are comprehensive and the blog posts actually rank on Google!",
    rating: 5,
    avatar: "ER"
  },
  {
    name: "David Park",
    role: "Network Producer",
    content: "We manage 15 podcasts and Podion AI has scaled our content production effortlessly. The time savings are incredible and the quality is consistently high.",
    rating: 5,
    avatar: "DP"
  }
];

export function TestimonialsSection() {
  return (
    <section className="py-20 blue-gradient-soft relative z-10">
      <div className="container mx-auto px-4">
        <div className="text-center mb-16 animate-fade-in-up">
          <h2 className="text-3xl lg:text-4xl font-bold text-gray-900 mb-4">
            Loved by 10,000+ Podcasters
          </h2>
          <p className="text-xl text-gray-600 max-w-2xl mx-auto">
            See how podcasters are transforming their content strategy with Podion AI
          </p>
        </div>
        
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
          {testimonials.map((testimonial, index) => (
            <Card key={index} className="card-gradient hover-lift border-0 shadow-lg animate-scale-in" style={{ animationDelay: `${index * 0.1}s` }}>
              <CardContent className="p-6">
                <div className="flex items-center gap-1 mb-4">
                  {Array.from({ length: testimonial.rating }).map((_, i) => (
                    <Star key={i} className="h-4 w-4 text-yellow-400 fill-current" />
                  ))}
                </div>
                
                <Quote className="h-8 w-8 text-blue-500 opacity-50 mb-4" />
                
                <p className="text-gray-700 mb-6 leading-relaxed">
                  "{testimonial.content}"
                </p>
                
                <div className="flex items-center gap-3">
                  <Avatar className="h-10 w-10">
                    <AvatarFallback className="bg-blue-100 text-blue-700 font-semibold">
                      {testimonial.avatar}
                    </AvatarFallback>
                  </Avatar>
                  <div>
                    <div className="font-semibold text-gray-900">{testimonial.name}</div>
                    <div className="text-sm text-gray-500">{testimonial.role}</div>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </section>
  );
}
